[package]
name = "cat_rs"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
assert_cmd = "2.1.1"
predicate = "0.1.0"
predicates = "3.1.3"
pretty_assertions = "1.4.1"
rand = "0.9.2"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
